/* Auto-generated by llvm_mode/Makefile: avoid macro collisions with LLVM */
#pragma once
/* SNPSFuzzer fork defines R(x) in ../types.h; LLVM headers use identifiers named R. */
#ifdef R
#undef R
#endif
