/* Auto-generated by llvm_mode/Makefile for LLVM>=9 compatibility */
#pragma once

/* Ensure legacy pass manager types are available */
#include <llvm/Pass.h>
#include <llvm/IR/LegacyPassManager.h>

/* The SNPSFuzzer tree defines AFL_R() under AFL_LLVM_PASS; the pass code calls R(). */
#ifndef R
#  ifdef AFL_R
#    define R(x) AFL_R(x)
#  endif
#endif

/* IRBuilder API shims (LLVM 8+ changed CreateLoad/CreateGEP signatures).
   These macros rewrite the old calls used by afl-llvm-pass.so.cc.
*/
#include <llvm/IR/IRBuilder.h>

/* CreateLoad(ptr) -> CreateLoad(ptr->getType()->getPointerElementType(), ptr) */
#define AFL_LLVM_CREATELOAD(IRB, PTR) (IRB).CreateLoad((PTR)->getType()->getPointerElementType(), (PTR))

/* CreateGEP(ptr, idx) -> CreateGEP(elementTy, ptr, idx) */
#define AFL_LLVM_CREATEGEP(IRB, PTR, IDX) (IRB).CreateGEP((PTR)->getType()->getPointerElementType(), (PTR), (IDX))

/* If the pass uses IRB.CreateLoad(x) / IRB.CreateGEP(x,y), remap those tokens.
   This is intentionally narrow: only matches the exact spellings used in old AFL pass code.
*/
#define CreateLoad(PTR) AFL_LLVM_CREATELOAD((*this), (PTR))
#define CreateGEP(PTR, IDX) AFL_LLVM_CREATEGEP((*this), (PTR), (IDX))
